Repository geosolutions-it/MapStore2-C040, pull requests merged in 2021-09, with the labels that each got.

#470 disable google maps API ping by default
  api.html
  apiTemplate.html
  dashboard-embedded-template.html
  dashboard-embedded.html
  embedded.html
  embeddedTemplate.html
  geostory-embedded-template.html
  geostory-embedded.html
  index.html
  indexTemplate.html
Labels: enhancement

#475 #471: Separate SPID login from Mapstore or LDAP login
  internal-login.html
  js/components/LoginModal.jsx
  js/components/__tests__/LoginModal-test.jsx
Labels: Priority: Blocker, Task, C040-COMUNE_GE-2021-SUPPORT

#487 Update basic auth rule to allow extension upload
  localConfig.json
Labels: bug, C040-COMUNE_GE-2021-SUPPORT
